---
title: "BioConductor y RStudio"
author: "DanteTorres"
date: "2/25/2021"
output: html_document
---

## Creando proyectos en R Studio:
Los proyectos sirven para tener un ambiente de trabajo más ordenado y fácil de trabajar. Se crean carpetas particulares parra los distintos tipos de datos de trabajo.

usethis::create_project("~/RNA_Seq_Notas2021")   #Crea el proyecto

usethis::use_r("01-notas.R") #Crea un archivo para empezar a trabajar dentro de la carpeta R

dir.create(here::here("figuras"), showWarnings = FALSE) #Crea un nuevo directorio "figuras" dentro del Proyecto.


## Introducción a BioConductor:
Elegir algunos paquetes de interés y hacer un breve resúmen sobre sus cualidades y desventajas. 

1.- **Bayesian Hidden Markov:** No hay preguntas, pasa las pruebas para todos pero no hay linux binario, pocas descargas pero puede ser porque es demasiado específico, buena documentacion. Calificacion final 8.

2.- **An R toolkit for non-coding RNA:** Fallo pruebas en linux, no hizo una pruebas en binario. No hay preguntas, buena documentacion, pocas descargas aun que sea mas general que el anterior. Calificacion final 7.

3.- **Toxico Genomic Data:** No hay preguntas, pasa pruebas para todos pero no hay linux binario, demasiadas dependencias, más descargas que los dos anteriores. Documentación MUY corta pero MUY bonita. Calificación final 8.5

4.- **ChromeSScape**: No tiene preguntas, muchísimas dependencias, pasó las pruebas pero no tiene linux binario. Muy buena y bonita documentación. Calificación final 9.5

5.- **Mutational Signature Comprehensive Analisis Toolkit:**  Muchas dependencias, se ve que no ha habido muchos cambios y la página puede estar un poco obsoleta. La documentacion está bonita y bien explicada.  Calificacion Final 8.5

6.- **VERSO:** Pocas dependencias, pasa todo los sistemas operativos menos el linux binario, es un paquete muy útil para la situación de ahorita pero es extrañamente poco descargado, no tiene documentación en HTML pero la tiene en PDF. Calificación Final 8.5

7.- **RIPAT:** Un número normal de dependencias, no hay preguntas, pasó todas las pruebas menos el linux binario y la documentación está MUY completa y bien explicada. Calificacion final 9.5

8.- **VELOCIRAPTOR:** Buen número de descargas y de dependencias, pasó todas las pruebas menos la de binario y la documentación es bonita y completa. Además tiene un buen nombre que apela al sentido del humor del usuario. Calificacion Final 9
